### ISSUE TITLE
path character issue

### ISSUE THREAD

**Issue by outtycast** [swargaraj/udemy-py#16]
having issue with a single course that has multiple brackets in the output_path and file name

it's the only course I'm having this issue with

I have seen this issue with another script before but not positive its the issue. 

however the full audio and video files are downloading to the temp folder

when the process_mpd.py util script gets to line 86, ffmpeg is used to merge audio and video but the output file produces is a 1KB file in the course folder. 

if pause before the ffmpeg merge can see the files are there and are complete.

I have attached screen shots and textfile with url

-----------
course_url
[courseurl.txt](https://github.com/user-attachments/files/17406754/courseurl.txt)

ss1
<img width="1126" alt="ss1" src="https://github.com/user-attachments/assets/9fea1609-19fa-4593-8c04-d40e5b0c3ff5">

ss2
<img width="679" alt="ss2-tempfiles" src="https://github.com/user-attachments/assets/618534e6-536b-4326-aaf9-45a03183afbb">

ss3
<img width="713" alt="ss3" src="https://github.com/user-attachments/assets/9ab694c3-a90c-47ec-b7c7-f3449098f013">

**Comment by swargaraj** [comment]
The course you are trying to download has DRM Protection. You need to add `--key` with the actual decryption key to be able to decrypt the video lectures.

Without Decryption Key:
![image](https://github.com/user-attachments/assets/51af5631-d820-498e-aeb2-0a7ed7eab127)

With Decryption Key:
![image](https://github.com/user-attachments/assets/390e3521-3d8e-4dbd-ae83-6bb559f2266d)

**Comment by outtycast** [comment]
will check again. maybe i have the wrong key.

**Comment by outtycast** [comment]
confirmed was the issue.
