### ISSUE TITLE
Request feature to download a single lecture from the course

### ISSUE THREAD

**Issue by bugbounted** [swargaraj/udemy-py#4]
Hi [swargaraj](https://github.com/swargaraj),
Request feature to download a specific lecture from the course
waiting for your commit/s or new branch
regards

**Comment by swargaraj** [comment]
Hey There! This feature will be added in the next release.

**Comment by swargaraj** [comment]
Thanks so much for your patience! I'm letting you know that this feature will be included in the next pull request. I appreciate your interest in improving the project!
